apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: puml
  description: |
    PUML a rust implementation of a PlantUML diagram rendering tool.
spec:
  type: cli
  system: developer-tools
  lifecycle: experimental
  owner: user:grahambrooks
  memberOf: [guests]
