# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Puml < Formula
  desc "Rust CLI reimplementation of PlantUML"
  homepage "https://github.com/grahambrooks/puml"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.9.2/puml-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "a00473e808dc74bfaaaf8f0071056af29bf8148ab59517e5a2f093450eda1e4c"
    end
    on_intel do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.9.2/puml-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "0e8527999edcfd983c2c23c3744f55ec2c15227bebb31cdbb89dc483452de45d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.9.2/puml-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4dcdfdc403a2ba5661d3e2762e6819e2512a0e1933b96a8519ec2a28e0f25331"
    end
    on_intel do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.9.2/puml-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3862397dfc8e3aece21518ffbba0d1a56d701e45a5bcce8a5968256faa46b939"
    end
  end

  def install
    bin.install "puml"
  end

  test do
    assert_path_exists bin/"puml"
  end
end
