# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Puml < Formula
  desc "Rust CLI reimplementation of PlantUML"
  homepage "https://github.com/grahambrooks/puml"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.10.1/puml-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "04c316c577751ad61cc3cfc8621c4b67084d557387bc7eca274ff3e68f84b525"
    end
    on_intel do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.10.1/puml-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "6b43322249d8d42440eec9432d83084991dc7827e80f546cf56859e433999383"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.10.1/puml-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c59164e9729d532269b6f40537826ba2690f95e27231a6fea6aba4b8a9a024f5"
    end
    on_intel do
      url "https://github.com/grahambrooks/puml/releases/download/v2026.10.1/puml-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6243435d20e3f96097619df5619ce6f2e97c589fe0ad13fdd9399b409d93a9d6"
    end
  end

  def install
    bin.install "puml"
  end

  test do
    assert_path_exists bin/"puml"
  end
end
